# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      ### ANGULAR PORTION ###

      # Download and cache dependencies
      - restore_cache:
          keys:
            - angular-dependencies-{{ checksum "closetr-web/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - angular-dependencies-

      - run:
          name: Installing Node Modules for Angular
          command: |
            cd closetr-web
            npm install

      - save_cache:
          paths:
            - closetr-web/node_modules
          key: angular-dependencies-{{ checksum "closetr-web/package.json" }}

      - run:
          name: Building Frontend from Angular
          command: |
            cd closetr-web
            npm build

      ### NODE/EXPRESS PORTION ###

      - restore_cache:
          keys:
            - express-dependencies-{{ checksum "closetr-api/package.json" }}
            - express-dependencies-

      - run:
          name: Installing Node Modules for Express
          command: |
            cd closetr-api
            npm install

      - save_cache:
          paths:
            - closetr-api/node_modules
          key: express-dependencies-{{ checksum "closetr-api/package.json" }}

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: |
            git subtree push --prefix closetr-web heroku master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
        filters:
          branches:
            only: master
